version: '3.2'
services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: 'Patata1.'
      ACCEPT_EULA: 'Y'
