version: '3.2'
services:
  api:
    container_name: api
    image: jruiz/wretro-api:${IMAGE_TAG}
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - SA_PASSWORD=${SA_PASSWORD}
    depends_on:
      - sql-server
    ports:
      - '8080:80'
    restart: always

  sql-server:
    container_name: sql-server
    image: jruiz/wretro-db:${IMAGE_TAG}
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
    restart: always