version: '3.2'
services:
  api:
    build:
      context: backend
    image: dotnet-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - sql-server
    ports:
      - '8080:80'

  sql-server:
    container_name: sql-server
    build:
      context: database
    environment:
      - SA_PASSWORD=Patata1.
    image: sql-server
