version: '3.2'
services:
  api:
    build:
      context: backend
    image: dotnet-server
    depends_on:
      - sql-server
    ports:
      - '8080:80'

  sql-server:
    container_name: sql-server
    build:
      context: database
    image: sql-server
