version: '3.2'
services:
  api:
    image: jruiz/wretro-api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - sql-server
    ports:
      - '8080:80'

  sql-server:
    container_name: sql-server
    image: jruiz/wretro-db:latest
    environment:
      - SA_PASSWORD=${PG_PASSWORD}
