/** Baseline */

USE master;
GO

CREATE DATABASE wretro;
GO

USE wretro;
GO

CREATE SCHEMA [wretro] AUTHORIZATION [dbo];
GO

CREATE TABLE wretro.Session
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY
);
GO

CREATE TABLE wretro.Card
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Title] NVARCHAR(100) NOT NULL,
	[SessionId] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT Fk_SessionId_CardId FOREIGN KEY (SessionId) REFERENCES wretro.Session (Id) ON DELETE CASCADE ON UPDATE CASCADE
);
GO

CREATE TABLE wretro.Comment
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Text] NVARCHAR(200) NOT NULL,
	[Likes] INT NOT NULL,
	[CardId] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT Fk_CardId_CommentId FOREIGN KEY (CardId) REFERENCES wretro.Card (Id) ON DELETE CASCADE ON UPDATE CASCADE
);
GO