name: Release workflow

on:
  release:
    types:
      - created

jobs:
  deploy:
    name: CD
    runs-on: ubuntu-latest
    steps:
      - name: ssh and docker-compose up
        run: |
          echo $"${{secrets.SSH_KEY}}" >> .ssh_key
          ssh -i .ssh_key -o StrictHostKeyChecking=no ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "docker-compose down; docker-compose up;"
