# This is a basic workflow to help you get started with Actions

name: wretro

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ci:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend
        run: |
          docker build -t ${{secrets.DOCKER_USER}}/wretro-api:${{github.ref:10}} backend/
          docker push ${{secrets.DOCKER_USER}}/wretro-api:${{github.ref:10}}

      - name: Build and push database
        run: |
          docker build -t ${{secrets.DOCKER_USER}}/wretro-db:${{github.ref:10}} database/
          docker push ${{secrets.DOCKER_USER}}/wretro-db:${{github.ref:10}}

      - name: Deploy to server
        run: |
          echo $"${{secrets.SSH_KEY}}" >> .ssh_key
          chmod 400 .ssh_key
          ssh -i .ssh_key -o StrictHostKeyChecking=no ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "cd projects/w-retro/; git pull; bash .github/deploy.sh ${{secrets.SA_PASSWORD}} ${{github.ref:10}}"
